# Generated by Django 6.0.4 on 2026-05-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nascimento', models.DateField()),
                ('cargo', models.IntegerField(choices=[(1, 'Veterinario'), (2, 'Financeiro'), (3, 'Atendimento')])),
            ],
        ),
    ]
